"""
Django settings for appsec_project project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key

BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
                                                                        
    pass


SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('DJANGO_DEBUG', 'True') == 'True':
        SECRET_KEY = get_random_secret_key()
        print("⚠️  WARNING: Using auto-generated SECRET_KEY. Set DJANGO_SECRET_KEY environment variable for production!")
    else:
        raise ValueError("DJANGO_SECRET_KEY environment variable must be set in production!")

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

                               
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']


                        

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'posts',
]

                   
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'appsec_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'appsec_project.wsgi.application'


          
                                                               

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'appsec_db'),
        'USER': os.environ.get('DB_USER', 'appsec_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'appsec_secret_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

                                                 
if not DEBUG and DATABASES['default']['PASSWORD'] == 'appsec_secret_password':
    raise ValueError("DB_PASSWORD environment variable must be set in production!")


                     
                                                                              

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


                      
                                                    

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

                       
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

                                        
                                                           

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

                                     
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

                                
                                                                        

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

                     
                                                                 
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@example.com'

                                                            
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False

                                 
                                                               
                                 
                  
                      
                                            
                                       

                   
                                  
                            
                                
                                       
                            
                              
                           

                  
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

                                        
                                                            
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)                                               
CSP_SCRIPT_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'",)                                         
CSP_FONT_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)                        
CSP_FORM_ACTION = ("'self'",)                             
CSP_BASE_URI = ("'self'",)                              
CSP_OBJECT_SRC = ("'none'",)                 
CSP_CONNECT_SRC = ("'self'",)                                       

                             
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

                       
SESSION_ENGINE = 'django.contrib.sessions.backends.db'                               
SESSION_COOKIE_AGE = 1800                           
SESSION_COOKIE_HTTPONLY = True                             
SESSION_COOKIE_SECURE = False                                        
SESSION_COOKIE_SAMESITE = 'Lax'                   
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True                                          

                                        
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]
